# Site settings
title: Vishnia's Testing Site
email: vishnia2001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vishnia.github.io" # the base hostname & protocol for your site
twitter_username: vishnia2001
github_username:  vishnia

# Build settings
markdown: kramdown
